
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelReservationInterface", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface HotelReservationInterface {


    /**
     * 
     * @param reservationLine
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MakeReservation", action = "http://tempuri.org/HotelReservationInterface/MakeReservation")
    @WebResult(name = "MakeReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MakeReservation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MakeReservation")
    @ResponseWrapper(localName = "MakeReservationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MakeReservationResponse")
    public String makeReservation(
        @WebParam(name = "ReservationLine", targetNamespace = "http://tempuri.org/")
        String reservationLine);

}
