
package org.travelmanagementsystem.hotelreservationinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelReservationInterface", targetNamespace = "http://travelmanagementsystem.org/hotelreservationinterface/", wsdlLocation = "http://192.168.0.108/HotelReservationService.asmx?WSDL")
public class HotelReservationInterface
    extends Service
{

    private final static URL HOTELRESERVATIONINTERFACE_WSDL_LOCATION;
    private final static WebServiceException HOTELRESERVATIONINTERFACE_EXCEPTION;
    private final static QName HOTELRESERVATIONINTERFACE_QNAME = new QName("http://travelmanagementsystem.org/hotelreservationinterface/", "HotelReservationInterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.108/HotelReservationService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELRESERVATIONINTERFACE_WSDL_LOCATION = url;
        HOTELRESERVATIONINTERFACE_EXCEPTION = e;
    }

    public HotelReservationInterface() {
        super(__getWsdlLocation(), HOTELRESERVATIONINTERFACE_QNAME);
    }

    public HotelReservationInterface(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELRESERVATIONINTERFACE_QNAME, features);
    }

    public HotelReservationInterface(URL wsdlLocation) {
        super(wsdlLocation, HOTELRESERVATIONINTERFACE_QNAME);
    }

    public HotelReservationInterface(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELRESERVATIONINTERFACE_QNAME, features);
    }

    public HotelReservationInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelReservationInterface(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelReservationInterfaceSoap
     */
    @WebEndpoint(name = "HotelReservationInterfaceSoap")
    public HotelReservationInterfaceSoap getHotelReservationInterfaceSoap() {
        return super.getPort(new QName("http://travelmanagementsystem.org/hotelreservationinterface/", "HotelReservationInterfaceSoap"), HotelReservationInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelReservationInterfaceSoap
     */
    @WebEndpoint(name = "HotelReservationInterfaceSoap")
    public HotelReservationInterfaceSoap getHotelReservationInterfaceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://travelmanagementsystem.org/hotelreservationinterface/", "HotelReservationInterfaceSoap"), HotelReservationInterfaceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns HotelReservationInterfaceSoap
     */
    @WebEndpoint(name = "HotelReservationInterfaceSoap12")
    public HotelReservationInterfaceSoap getHotelReservationInterfaceSoap12() {
        return super.getPort(new QName("http://travelmanagementsystem.org/hotelreservationinterface/", "HotelReservationInterfaceSoap12"), HotelReservationInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelReservationInterfaceSoap
     */
    @WebEndpoint(name = "HotelReservationInterfaceSoap12")
    public HotelReservationInterfaceSoap getHotelReservationInterfaceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://travelmanagementsystem.org/hotelreservationinterface/", "HotelReservationInterfaceSoap12"), HotelReservationInterfaceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELRESERVATIONINTERFACE_EXCEPTION!= null) {
            throw HOTELRESERVATIONINTERFACE_EXCEPTION;
        }
        return HOTELRESERVATIONINTERFACE_WSDL_LOCATION;
    }

}
