
package org.travelmanagementsystem.hotelreservationinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelReservationInterfaceSoap", targetNamespace = "http://travelmanagementsystem.org/hotelreservationinterface/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelReservationInterfaceSoap {


    /**
     * 
     * @param reservationLine
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MakeReservation", action = "http://travelmanagementsystem.org/hotelreservationinterface/MakeReservation")
    @WebResult(name = "MakeReservationResult", targetNamespace = "http://travelmanagementsystem.org/hotelreservationinterface/")
    @RequestWrapper(localName = "MakeReservation", targetNamespace = "http://travelmanagementsystem.org/hotelreservationinterface/", className = "org.travelmanagementsystem.hotelreservationinterface.MakeReservation")
    @ResponseWrapper(localName = "MakeReservationResponse", targetNamespace = "http://travelmanagementsystem.org/hotelreservationinterface/", className = "org.travelmanagementsystem.hotelreservationinterface.MakeReservationResponse")
    public String makeReservation(
        @WebParam(name = "ReservationLine", targetNamespace = "http://travelmanagementsystem.org/hotelreservationinterface/")
        String reservationLine);

}
